/* Generated by Yosys 0.9 (git sha1 1979e0b, g++-9 9.5.0-1ubuntu1~22.04.1 -fPIC -Os) */

(* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:109" *)
module GcdUnitCtrlRTL_0x4d0fc71ead8d3d9e(a_mux_sel, a_reg_en, b_mux_sel, b_reg_en, clk, is_a_lt_b, is_b_zero, req_rdy, req_val, reset, resp_rdy, resp_val);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:111" *)
  output [1:0] a_mux_sel;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:112" *)
  output a_reg_en;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:113" *)
  output b_mux_sel;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:114" *)
  output b_reg_en;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:115" *)
  input clk;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:126" *)
  wire [1:0] curr_state__0;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:127" *)
  wire [1:0] current_state__1;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:116" *)
  input is_a_lt_b;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:117" *)
  input is_b_zero;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:130" *)
  wire [1:0] next_state__0;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:118" *)
  output req_rdy;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:119" *)
  input req_val;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:120" *)
  input reset;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:121" *)
  input resp_rdy;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:122" *)
  output resp_val;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:147" *)
  wire \state$clk ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:131" *)
  wire [1:0] \state$in_ ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:148" *)
  wire [1:0] \state$out ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:146" *)
  wire \state$reset ;
  INVR01 _05_ (
    .IN1(\state$out [1]),
    .OUT1(a_reg_en)
  );
  INVR01 _06_ (
    .IN1(\state$out [0]),
    .OUT1(_00_)
  );
  INVR01 _07_ (
    .IN1(is_b_zero),
    .OUT1(_01_)
  );
  INVR01 _08_ (
    .IN1(is_a_lt_b),
    .OUT1(_02_)
  );
  NOR200 _09_ (
    .IN1(\state$out [1]),
    .IN2(\state$out [0]),
    .OUT1(b_mux_sel)
  );
  NOR200 _10_ (
    .IN1(a_reg_en),
    .IN2(\state$out [0]),
    .OUT1(resp_val)
  );
  NOR300 _11_ (
    .IN1(\state$out [1]),
    .IN2(_00_),
    .IN3(_02_),
    .OUT1(a_mux_sel[1])
  );
  OR2101 _12_ (
    .IN1(b_mux_sel),
    .IN2(a_mux_sel[1]),
    .OUT1(b_reg_en)
  );
  NOR300 _13_ (
    .IN1(\state$out [1]),
    .IN2(_00_),
    .IN3(is_a_lt_b),
    .OUT1(a_mux_sel[0])
  );
  OR4101 _14_ (
    .IN1(\state$out [1]),
    .IN2(_00_),
    .IN3(_01_),
    .IN4(is_a_lt_b),
    .OUT1(_03_)
  );
  ADNR01 _15_ (
    .A(a_reg_en),
    .B(req_val),
    .C(\state$out [0]),
    .OUT1(_04_)
  );
  ADNR01 _16_ (
    .A(is_b_zero),
    .B(a_mux_sel[0]),
    .C(_04_),
    .OUT1(\state$in_ [0])
  );
  AOI401 _17_ (
    .A(resp_rdy),
    .B(resp_val),
    .C(_03_),
    .D(a_reg_en),
    .OUT1(\state$in_ [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:150" *)
  RegRst_0x9f365fdf6c8998a state (
    .clk(clk),
    .in_(\state$in_ ),
    .out(\state$out ),
    .reset(reset)
  );
  assign curr_state__0 = \state$out ;
  assign current_state__1 = \state$out ;
  assign next_state__0 = \state$in_ ;
  assign req_rdy = b_mux_sel;
  assign \state$clk  = clk;
  assign \state$reset  = reset;
endmodule

(* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:369" *)
module GcdUnitDpathRTL_0x4d0fc71ead8d3d9e(a_mux_sel, a_reg_en, b_mux_sel, b_reg_en, clk, is_a_lt_b, is_b_zero, req_msg_a, req_msg_b, reset, resp_msg);
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:407" *)
  wire \a_lt_b$clk ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:408" *)
  wire [15:0] \a_lt_b$in0 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:409" *)
  wire [15:0] \a_lt_b$in1 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:410" *)
  wire \a_lt_b$out ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:406" *)
  wire \a_lt_b$reset ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:440" *)
  wire \a_mux$clk ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:437" *)
  wire [15:0] \a_mux$in_$000 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:438" *)
  wire [15:0] \a_mux$in_$001 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:439" *)
  wire [15:0] \a_mux$in_$002 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:442" *)
  wire [15:0] \a_mux$out ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:436" *)
  wire \a_mux$reset ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:441" *)
  wire [1:0] \a_mux$sel ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:371" *)
  input [1:0] a_mux_sel;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:392" *)
  wire \a_reg$clk ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:393" *)
  wire \a_reg$en ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:391" *)
  wire [15:0] \a_reg$in_ ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:394" *)
  wire [15:0] \a_reg$out ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:390" *)
  wire \a_reg$reset ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:372" *)
  input a_reg_en;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:459" *)
  wire \b_mux$clk ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:457" *)
  wire [15:0] \b_mux$in_$000 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:458" *)
  wire [15:0] \b_mux$in_$001 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:461" *)
  wire [15:0] \b_mux$out ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:456" *)
  wire \b_mux$reset ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:460" *)
  wire \b_mux$sel ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:373" *)
  input b_mux_sel;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:492" *)
  wire \b_reg$clk ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:493" *)
  wire \b_reg$en ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:491" *)
  wire [15:0] \b_reg$in_ ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:494" *)
  wire [15:0] \b_reg$out ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:490" *)
  wire \b_reg$reset ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:374" *)
  input b_reg_en;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:386" *)
  wire [15:0] b_reg_out;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:424" *)
  wire \b_zero$clk ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:423" *)
  wire [15:0] \b_zero$in_ ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:425" *)
  wire \b_zero$out ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:422" *)
  wire \b_zero$reset ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:375" *)
  input clk;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:376" *)
  output is_a_lt_b;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:377" *)
  output is_b_zero;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:378" *)
  input [15:0] req_msg_a;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:379" *)
  input [15:0] req_msg_b;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:380" *)
  input reset;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:381" *)
  output [15:0] resp_msg;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:475" *)
  wire \sub$clk ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:476" *)
  wire [15:0] \sub$in0 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:477" *)
  wire [15:0] \sub$in1 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:478" *)
  wire [15:0] \sub$out ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:474" *)
  wire \sub$reset ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:385" *)
  wire [15:0] sub_out;
  (* module_not_derived = 32'd1 *)
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:412" *)
  LtComparator_0x422b1f52edd46a85 a_lt_b (
    .clk(clk),
    .in0(\a_lt_b$in0 ),
    .in1(\a_lt_b$in1 ),
    .out(\a_lt_b$out ),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:444" *)
  Mux_0x683fa1a418b072c9 a_mux (
    .clk(clk),
    .\in_$000 (req_msg_a),
    .\in_$001 (\a_mux$in_$001 ),
    .\in_$002 (\a_lt_b$in1 ),
    .out(\a_mux$out ),
    .reset(reset),
    .sel(a_mux_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:396" *)
  RegEn_0x68db79c4ec1d6e5b a_reg (
    .clk(clk),
    .en(a_reg_en),
    .in_(\a_mux$out ),
    .out(\a_lt_b$in0 ),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:463" *)
  Mux_0xdd6473406d1a99a b_mux (
    .clk(clk),
    .\in_$000 (\a_lt_b$in0 ),
    .\in_$001 (req_msg_b),
    .out(\b_mux$out ),
    .reset(reset),
    .sel(b_mux_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:496" *)
  RegEn_0x68db79c4ec1d6e5b b_reg (
    .clk(clk),
    .en(b_reg_en),
    .in_(\b_mux$out ),
    .out(\a_lt_b$in1 ),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:427" *)
  ZeroComparator_0x422b1f52edd46a85 b_zero (
    .clk(clk),
    .in_(\a_lt_b$in1 ),
    .out(\b_zero$out ),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:480" *)
  Subtractor_0x422b1f52edd46a85 sub (
    .clk(clk),
    .in0(\a_lt_b$in0 ),
    .in1(\a_lt_b$in1 ),
    .out(\a_mux$in_$001 ),
    .reset(reset)
  );
  assign \a_lt_b$clk  = clk;
  assign \a_lt_b$reset  = reset;
  assign \a_mux$clk  = clk;
  assign \a_mux$in_$000  = req_msg_a;
  assign \a_mux$in_$002  = \a_lt_b$in1 ;
  assign \a_mux$reset  = reset;
  assign \a_mux$sel  = a_mux_sel;
  assign \a_reg$clk  = clk;
  assign \a_reg$en  = a_reg_en;
  assign \a_reg$in_  = \a_mux$out ;
  assign \a_reg$out  = \a_lt_b$in0 ;
  assign \a_reg$reset  = reset;
  assign \b_mux$clk  = clk;
  assign \b_mux$in_$000  = \a_lt_b$in0 ;
  assign \b_mux$in_$001  = req_msg_b;
  assign \b_mux$reset  = reset;
  assign \b_mux$sel  = b_mux_sel;
  assign \b_reg$clk  = clk;
  assign \b_reg$en  = b_reg_en;
  assign \b_reg$in_  = \b_mux$out ;
  assign \b_reg$out  = \a_lt_b$in1 ;
  assign \b_reg$reset  = reset;
  assign b_reg_out = \a_lt_b$in1 ;
  assign \b_zero$clk  = clk;
  assign \b_zero$in_  = \a_lt_b$in1 ;
  assign \b_zero$reset  = reset;
  assign is_a_lt_b = \a_lt_b$out ;
  assign is_b_zero = \b_zero$out ;
  assign resp_msg = \a_mux$in_$001 ;
  assign \sub$clk  = clk;
  assign \sub$in0  = \a_lt_b$in0 ;
  assign \sub$in1  = \a_lt_b$in1 ;
  assign \sub$out  = \a_mux$in_$001 ;
  assign \sub$reset  = reset;
  assign sub_out = \a_mux$in_$001 ;
endmodule

(* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:588" *)
module LtComparator_0x422b1f52edd46a85(clk, in0, in1, out, reset);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:590" *)
  input clk;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:591" *)
  input [15:0] in0;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:592" *)
  input [15:0] in1;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:593" *)
  output out;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:594" *)
  input reset;
  INVR01 _062_ (
    .IN1(in1[2]),
    .OUT1(_000_)
  );
  INVR01 _063_ (
    .IN1(in1[5]),
    .OUT1(_001_)
  );
  INVR01 _064_ (
    .IN1(in1[6]),
    .OUT1(_002_)
  );
  INVR01 _065_ (
    .IN1(in1[10]),
    .OUT1(_003_)
  );
  INVR01 _066_ (
    .IN1(in1[11]),
    .OUT1(_004_)
  );
  INVR01 _067_ (
    .IN1(in1[13]),
    .OUT1(_005_)
  );
  INVR01 _068_ (
    .IN1(in1[15]),
    .OUT1(_006_)
  );
  INVR01 _069_ (
    .IN1(in0[0]),
    .OUT1(_007_)
  );
  INVR01 _070_ (
    .IN1(in0[1]),
    .OUT1(_008_)
  );
  INVR01 _071_ (
    .IN1(in0[3]),
    .OUT1(_009_)
  );
  INVR01 _072_ (
    .IN1(in0[4]),
    .OUT1(_010_)
  );
  INVR01 _073_ (
    .IN1(in0[7]),
    .OUT1(_011_)
  );
  INVR01 _074_ (
    .IN1(in0[8]),
    .OUT1(_012_)
  );
  INVR01 _075_ (
    .IN1(in0[9]),
    .OUT1(_013_)
  );
  INVR01 _076_ (
    .IN1(in0[12]),
    .OUT1(_014_)
  );
  INVR01 _077_ (
    .IN1(in0[14]),
    .OUT1(_015_)
  );
  OR2101 _078_ (
    .IN1(_002_),
    .IN2(in0[6]),
    .OUT1(_016_)
  );
  NOR200 _079_ (
    .IN1(in1[1]),
    .IN2(_008_),
    .OUT1(_017_)
  );
  NND201 _080_ (
    .IN1(in1[3]),
    .IN2(_009_),
    .OUT1(_018_)
  );
  AOI401 _081_ (
    .A(in1[0]),
    .B(_007_),
    .C(_008_),
    .D(in1[1]),
    .OUT1(_019_)
  );
  XOR201 _082_ (
    .IN1(in1[2]),
    .IN2(in0[2]),
    .OUT1(_020_)
  );
  ADNR01 _083_ (
    .A(in1[3]),
    .B(_009_),
    .C(_020_),
    .OUT1(_021_)
  );
  ORND01 _084_ (
    .A(_017_),
    .B(_019_),
    .C(_021_),
    .OUT1(_022_)
  );
  NND300 _085_ (
    .IN1(_000_),
    .IN2(in0[2]),
    .IN3(_018_),
    .OUT1(_023_)
  );
  NOR200 _086_ (
    .IN1(in1[4]),
    .IN2(_010_),
    .OUT1(_024_)
  );
  NOR200 _087_ (
    .IN1(in1[3]),
    .IN2(_009_),
    .OUT1(_025_)
  );
  NOR200 _088_ (
    .IN1(_024_),
    .IN2(_025_),
    .OUT1(_026_)
  );
  NND300 _089_ (
    .IN1(_022_),
    .IN2(_023_),
    .IN3(_026_),
    .OUT1(_027_)
  );
  NOR200 _090_ (
    .IN1(_001_),
    .IN2(in0[5]),
    .OUT1(_028_)
  );
  ADNR01 _091_ (
    .A(in1[4]),
    .B(_010_),
    .C(_028_),
    .OUT1(_029_)
  );
  NOR200 _092_ (
    .IN1(in1[7]),
    .IN2(_011_),
    .OUT1(_030_)
  );
  ADOR16 _093_ (
    .A(_001_),
    .B(in0[5]),
    .C(_027_),
    .D(_029_),
    .E(in0[6]),
    .F(_002_),
    .OUT1(_031_)
  );
  ADNR01 _094_ (
    .A(_016_),
    .B(_031_),
    .C(_030_),
    .OUT1(_032_)
  );
  NND201 _095_ (
    .IN1(_004_),
    .IN2(in0[11]),
    .OUT1(_033_)
  );
  ORND01 _096_ (
    .A(_003_),
    .B(in0[10]),
    .C(_033_),
    .OUT1(_034_)
  );
  NOR200 _097_ (
    .IN1(_004_),
    .IN2(in0[11]),
    .OUT1(_035_)
  );
  AND201 _098_ (
    .IN1(_003_),
    .IN2(in0[10]),
    .OUT1(_036_)
  );
  INVR01 _099_ (
    .IN1(_036_),
    .OUT1(_037_)
  );
  OR3101 _100_ (
    .IN1(_034_),
    .IN2(_035_),
    .IN3(_036_),
    .OUT1(_038_)
  );
  ADNR01 _101_ (
    .A(in1[9]),
    .B(_013_),
    .C(_038_),
    .OUT1(_039_)
  );
  NOR200 _102_ (
    .IN1(in1[9]),
    .IN2(_013_),
    .OUT1(_040_)
  );
  NOR200 _103_ (
    .IN1(in1[8]),
    .IN2(_012_),
    .OUT1(_041_)
  );
  OR2101 _104_ (
    .IN1(_040_),
    .IN2(_041_),
    .OUT1(_042_)
  );
  ADOR16 _105_ (
    .A(in1[7]),
    .B(_011_),
    .C(_012_),
    .D(in1[8]),
    .E(_013_),
    .F(in1[9]),
    .OUT1(_043_)
  );
  OR3101 _106_ (
    .IN1(_038_),
    .IN2(_042_),
    .IN3(_043_),
    .OUT1(_044_)
  );
  ORND01 _107_ (
    .A(_035_),
    .B(_037_),
    .C(_033_),
    .OUT1(_045_)
  );
  ADNR01 _108_ (
    .A(_039_),
    .B(_042_),
    .C(_045_),
    .OUT1(_046_)
  );
  ORND01 _109_ (
    .A(_032_),
    .B(_044_),
    .C(_046_),
    .OUT1(_047_)
  );
  NND201 _110_ (
    .IN1(_006_),
    .IN2(in0[15]),
    .OUT1(_048_)
  );
  ORND01 _111_ (
    .A(in1[14]),
    .B(_015_),
    .C(_048_),
    .OUT1(_049_)
  );
  NOR200 _112_ (
    .IN1(_006_),
    .IN2(in0[15]),
    .OUT1(_050_)
  );
  AND201 _113_ (
    .IN1(in1[14]),
    .IN2(_015_),
    .OUT1(_051_)
  );
  OR3101 _114_ (
    .IN1(_049_),
    .IN2(_050_),
    .IN3(_051_),
    .OUT1(_052_)
  );
  NND201 _115_ (
    .IN1(_005_),
    .IN2(in0[13]),
    .OUT1(_053_)
  );
  ORND01 _116_ (
    .A(in1[12]),
    .B(_014_),
    .C(_053_),
    .OUT1(_054_)
  );
  OR2101 _117_ (
    .IN1(_005_),
    .IN2(in0[13]),
    .OUT1(_055_)
  );
  NND201 _118_ (
    .IN1(in1[12]),
    .IN2(_014_),
    .OUT1(_056_)
  );
  NND201 _119_ (
    .IN1(_055_),
    .IN2(_056_),
    .OUT1(_057_)
  );
  NOR300 _120_ (
    .IN1(_052_),
    .IN2(_054_),
    .IN3(_057_),
    .OUT1(_058_)
  );
  ORND01 _121_ (
    .A(_006_),
    .B(in0[15]),
    .C(_049_),
    .OUT1(_059_)
  );
  NND201 _122_ (
    .IN1(_054_),
    .IN2(_055_),
    .OUT1(_060_)
  );
  ORND01 _123_ (
    .A(_052_),
    .B(_060_),
    .C(_059_),
    .OUT1(_061_)
  );
  ADNR01 _124_ (
    .A(_047_),
    .B(_058_),
    .C(_061_),
    .OUT1(out)
  );
endmodule

(* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:650" *)
module Mux_0x683fa1a418b072c9(clk, \in_$000 , \in_$001 , \in_$002 , out, reset, sel);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:652" *)
  input clk;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:653" *)
  input [15:0] \in_$000 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:654" *)
  input [15:0] \in_$001 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:655" *)
  input [15:0] \in_$002 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:650" *)
  wire [15:0] \in_[0] ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:650" *)
  wire [15:0] \in_[1] ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:650" *)
  wire [15:0] \in_[2] ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:656" *)
  output [15:0] out;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:657" *)
  input reset;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:658" *)
  input [1:0] sel;
  INVR01 _04_ (
    .IN1(sel[1]),
    .OUT1(_00_)
  );
  NOR200 _05_ (
    .IN1(sel[0]),
    .IN2(_00_),
    .OUT1(_01_)
  );
  NOR200 _06_ (
    .IN1(sel[0]),
    .IN2(sel[1]),
    .OUT1(_02_)
  );
  AND201 _07_ (
    .IN1(sel[0]),
    .IN2(_00_),
    .OUT1(_03_)
  );
  ADOR16 _08_ (
    .A(\in_$000 [0]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [0]),
    .E(\in_$002 [0]),
    .F(_01_),
    .OUT1(out[0])
  );
  ADOR16 _09_ (
    .A(\in_$000 [1]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [1]),
    .E(\in_$002 [1]),
    .F(_01_),
    .OUT1(out[1])
  );
  ADOR16 _10_ (
    .A(\in_$000 [2]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [2]),
    .E(\in_$002 [2]),
    .F(_01_),
    .OUT1(out[2])
  );
  ADOR16 _11_ (
    .A(\in_$000 [3]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [3]),
    .E(\in_$002 [3]),
    .F(_01_),
    .OUT1(out[3])
  );
  ADOR16 _12_ (
    .A(\in_$000 [4]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [4]),
    .E(\in_$002 [4]),
    .F(_01_),
    .OUT1(out[4])
  );
  ADOR16 _13_ (
    .A(\in_$000 [5]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [5]),
    .E(\in_$002 [5]),
    .F(_01_),
    .OUT1(out[5])
  );
  ADOR16 _14_ (
    .A(\in_$000 [6]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [6]),
    .E(\in_$002 [6]),
    .F(_01_),
    .OUT1(out[6])
  );
  ADOR16 _15_ (
    .A(\in_$000 [7]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [7]),
    .E(\in_$002 [7]),
    .F(_01_),
    .OUT1(out[7])
  );
  ADOR16 _16_ (
    .A(\in_$000 [8]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [8]),
    .E(\in_$002 [8]),
    .F(_01_),
    .OUT1(out[8])
  );
  ADOR16 _17_ (
    .A(\in_$000 [9]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [9]),
    .E(\in_$002 [9]),
    .F(_01_),
    .OUT1(out[9])
  );
  ADOR16 _18_ (
    .A(\in_$000 [10]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [10]),
    .E(\in_$002 [10]),
    .F(_01_),
    .OUT1(out[10])
  );
  ADOR16 _19_ (
    .A(\in_$000 [11]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [11]),
    .E(\in_$002 [11]),
    .F(_01_),
    .OUT1(out[11])
  );
  ADOR16 _20_ (
    .A(\in_$000 [12]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [12]),
    .E(\in_$002 [12]),
    .F(_01_),
    .OUT1(out[12])
  );
  ADOR16 _21_ (
    .A(\in_$000 [13]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [13]),
    .E(\in_$002 [13]),
    .F(_01_),
    .OUT1(out[13])
  );
  ADOR16 _22_ (
    .A(\in_$000 [14]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [14]),
    .E(\in_$002 [14]),
    .F(_01_),
    .OUT1(out[14])
  );
  ADOR16 _23_ (
    .A(\in_$000 [15]),
    .B(_02_),
    .C(_03_),
    .D(\in_$001 [15]),
    .E(\in_$002 [15]),
    .F(_01_),
    .OUT1(out[15])
  );
  assign \in_[0]  = \in_$000 ;
  assign \in_[1]  = \in_$001 ;
  assign \in_[2]  = \in_$002 ;
endmodule

(* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:693" *)
module Mux_0xdd6473406d1a99a(clk, \in_$000 , \in_$001 , out, reset, sel);
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:695" *)
  input clk;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:696" *)
  input [15:0] \in_$000 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:697" *)
  input [15:0] \in_$001 ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:693" *)
  wire [15:0] \in_[0] ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:693" *)
  wire [15:0] \in_[1] ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:698" *)
  output [15:0] out;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:699" *)
  input reset;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:700" *)
  input sel;
  MX2101 _00_ (
    .A0(sel),
    .D0(\in_$000 [15]),
    .D1(\in_$001 [15]),
    .OUT1(out[15])
  );
  MX2101 _01_ (
    .A0(sel),
    .D0(\in_$000 [14]),
    .D1(\in_$001 [14]),
    .OUT1(out[14])
  );
  MX2101 _02_ (
    .A0(sel),
    .D0(\in_$000 [13]),
    .D1(\in_$001 [13]),
    .OUT1(out[13])
  );
  MX2101 _03_ (
    .A0(sel),
    .D0(\in_$000 [12]),
    .D1(\in_$001 [12]),
    .OUT1(out[12])
  );
  MX2101 _04_ (
    .A0(sel),
    .D0(\in_$000 [11]),
    .D1(\in_$001 [11]),
    .OUT1(out[11])
  );
  MX2101 _05_ (
    .A0(sel),
    .D0(\in_$000 [10]),
    .D1(\in_$001 [10]),
    .OUT1(out[10])
  );
  MX2101 _06_ (
    .A0(sel),
    .D0(\in_$000 [9]),
    .D1(\in_$001 [9]),
    .OUT1(out[9])
  );
  MX2101 _07_ (
    .A0(sel),
    .D0(\in_$000 [8]),
    .D1(\in_$001 [8]),
    .OUT1(out[8])
  );
  MX2101 _08_ (
    .A0(sel),
    .D0(\in_$000 [7]),
    .D1(\in_$001 [7]),
    .OUT1(out[7])
  );
  MX2101 _09_ (
    .A0(sel),
    .D0(\in_$000 [6]),
    .D1(\in_$001 [6]),
    .OUT1(out[6])
  );
  MX2101 _10_ (
    .A0(sel),
    .D0(\in_$000 [5]),
    .D1(\in_$001 [5]),
    .OUT1(out[5])
  );
  MX2101 _11_ (
    .A0(sel),
    .D0(\in_$000 [4]),
    .D1(\in_$001 [4]),
    .OUT1(out[4])
  );
  MX2101 _12_ (
    .A0(sel),
    .D0(\in_$000 [3]),
    .D1(\in_$001 [3]),
    .OUT1(out[3])
  );
  MX2101 _13_ (
    .A0(sel),
    .D0(\in_$000 [2]),
    .D1(\in_$001 [2]),
    .OUT1(out[2])
  );
  MX2101 _14_ (
    .A0(sel),
    .D0(\in_$000 [1]),
    .D1(\in_$001 [1]),
    .OUT1(out[1])
  );
  MX2101 _15_ (
    .A0(sel),
    .D0(\in_$000 [0]),
    .D1(\in_$001 [0]),
    .OUT1(out[0])
  );
  assign \in_[0]  = \in_$000 ;
  assign \in_[1]  = \in_$001 ;
endmodule

(* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:552" *)
module RegEn_0x68db79c4ec1d6e5b(clk, en, in_, out, reset);
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  wire [15:0] _00_;
  (* unused_bits = "0" *)
  wire _01_;
  (* unused_bits = "0" *)
  wire _02_;
  (* unused_bits = "0" *)
  wire _03_;
  (* unused_bits = "0" *)
  wire _04_;
  (* unused_bits = "0" *)
  wire _05_;
  (* unused_bits = "0" *)
  wire _06_;
  (* unused_bits = "0" *)
  wire _07_;
  (* unused_bits = "0" *)
  wire _08_;
  (* unused_bits = "0" *)
  wire _09_;
  (* unused_bits = "0" *)
  wire _10_;
  (* unused_bits = "0" *)
  wire _11_;
  (* unused_bits = "0" *)
  wire _12_;
  (* unused_bits = "0" *)
  wire _13_;
  (* unused_bits = "0" *)
  wire _14_;
  (* unused_bits = "0" *)
  wire _15_;
  (* unused_bits = "0" *)
  wire _16_;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:554" *)
  input clk;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:555" *)
  input en;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:556" *)
  input [15:0] in_;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:557" *)
  output [15:0] out;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:558" *)
  input reset;
  MX2101 _17_ (
    .A0(en),
    .D0(out[1]),
    .D1(in_[1]),
    .OUT1(_00_[1])
  );
  MX2101 _18_ (
    .A0(en),
    .D0(out[2]),
    .D1(in_[2]),
    .OUT1(_00_[2])
  );
  MX2101 _19_ (
    .A0(en),
    .D0(out[3]),
    .D1(in_[3]),
    .OUT1(_00_[3])
  );
  MX2101 _20_ (
    .A0(en),
    .D0(out[4]),
    .D1(in_[4]),
    .OUT1(_00_[4])
  );
  MX2101 _21_ (
    .A0(en),
    .D0(out[5]),
    .D1(in_[5]),
    .OUT1(_00_[5])
  );
  MX2101 _22_ (
    .A0(en),
    .D0(out[6]),
    .D1(in_[6]),
    .OUT1(_00_[6])
  );
  MX2101 _23_ (
    .A0(en),
    .D0(out[7]),
    .D1(in_[7]),
    .OUT1(_00_[7])
  );
  MX2101 _24_ (
    .A0(en),
    .D0(out[8]),
    .D1(in_[8]),
    .OUT1(_00_[8])
  );
  MX2101 _25_ (
    .A0(en),
    .D0(out[9]),
    .D1(in_[9]),
    .OUT1(_00_[9])
  );
  MX2101 _26_ (
    .A0(en),
    .D0(out[10]),
    .D1(in_[10]),
    .OUT1(_00_[10])
  );
  MX2101 _27_ (
    .A0(en),
    .D0(out[11]),
    .D1(in_[11]),
    .OUT1(_00_[11])
  );
  MX2101 _28_ (
    .A0(en),
    .D0(out[12]),
    .D1(in_[12]),
    .OUT1(_00_[12])
  );
  MX2101 _29_ (
    .A0(en),
    .D0(out[13]),
    .D1(in_[13]),
    .OUT1(_00_[13])
  );
  MX2101 _30_ (
    .A0(en),
    .D0(out[14]),
    .D1(in_[14]),
    .OUT1(_00_[14])
  );
  MX2101 _31_ (
    .A0(en),
    .D0(out[15]),
    .D1(in_[15]),
    .OUT1(_00_[15])
  );
  MX2101 _32_ (
    .A0(en),
    .D0(out[0]),
    .D1(in_[0]),
    .OUT1(_00_[0])
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _33_ (
    .C(clk),
    .D(_00_[0]),
    .Q(out[0]),
    .QB(_01_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _34_ (
    .C(clk),
    .D(_00_[1]),
    .Q(out[1]),
    .QB(_02_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _35_ (
    .C(clk),
    .D(_00_[2]),
    .Q(out[2]),
    .QB(_03_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _36_ (
    .C(clk),
    .D(_00_[3]),
    .Q(out[3]),
    .QB(_04_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _37_ (
    .C(clk),
    .D(_00_[4]),
    .Q(out[4]),
    .QB(_05_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _38_ (
    .C(clk),
    .D(_00_[5]),
    .Q(out[5]),
    .QB(_06_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _39_ (
    .C(clk),
    .D(_00_[6]),
    .Q(out[6]),
    .QB(_07_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _40_ (
    .C(clk),
    .D(_00_[7]),
    .Q(out[7]),
    .QB(_08_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _41_ (
    .C(clk),
    .D(_00_[8]),
    .Q(out[8]),
    .QB(_09_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _42_ (
    .C(clk),
    .D(_00_[9]),
    .Q(out[9]),
    .QB(_10_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _43_ (
    .C(clk),
    .D(_00_[10]),
    .Q(out[10]),
    .QB(_11_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _44_ (
    .C(clk),
    .D(_00_[11]),
    .Q(out[11]),
    .QB(_12_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _45_ (
    .C(clk),
    .D(_00_[12]),
    .Q(out[12]),
    .QB(_13_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _46_ (
    .C(clk),
    .D(_00_[13]),
    .Q(out[13]),
    .QB(_14_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _47_ (
    .C(clk),
    .D(_00_[14]),
    .Q(out[14]),
    .QB(_15_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:571" *)
  DFFL11 _48_ (
    .C(clk),
    .D(_00_[15]),
    .Q(out[15]),
    .QB(_16_)
  );
endmodule

(* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:329" *)
module RegRst_0x9f365fdf6c8998a(clk, in_, out, reset);
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:352" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  (* unused_bits = "0" *)
  wire _03_;
  (* unused_bits = "0" *)
  wire _04_;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:331" *)
  input clk;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:332" *)
  input [1:0] in_;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:333" *)
  output [1:0] out;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:334" *)
  input reset;
  INVR01 _05_ (
    .IN1(in_[1]),
    .OUT1(_01_)
  );
  INVR01 _06_ (
    .IN1(in_[0]),
    .OUT1(_02_)
  );
  NOR200 _07_ (
    .IN1(_01_),
    .IN2(reset),
    .OUT1(_00_[1])
  );
  NOR200 _08_ (
    .IN1(reset),
    .IN2(_02_),
    .OUT1(_00_[0])
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:352" *)
  DFFL11 _09_ (
    .C(clk),
    .D(_00_[0]),
    .Q(out[0]),
    .QB(_03_)
  );
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:352" *)
  DFFL11 _10_ (
    .C(clk),
    .D(_00_[1]),
    .Q(out[1]),
    .QB(_04_)
  );
endmodule

(* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:733" *)
module Subtractor_0x422b1f52edd46a85(clk, in0, in1, out, reset);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:735" *)
  input clk;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:736" *)
  input [15:0] in0;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:737" *)
  input [15:0] in1;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:738" *)
  output [15:0] out;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:739" *)
  input reset;
  INVR01 _085_ (
    .IN1(in1[0]),
    .OUT1(_040_)
  );
  INVR01 _086_ (
    .IN1(in1[1]),
    .OUT1(_041_)
  );
  INVR01 _087_ (
    .IN1(in1[3]),
    .OUT1(_042_)
  );
  INVR01 _088_ (
    .IN1(in1[5]),
    .OUT1(_043_)
  );
  INVR01 _089_ (
    .IN1(in0[2]),
    .OUT1(_044_)
  );
  INVR01 _090_ (
    .IN1(in0[4]),
    .OUT1(_045_)
  );
  INVR01 _091_ (
    .IN1(in0[6]),
    .OUT1(_046_)
  );
  INVR01 _092_ (
    .IN1(in0[7]),
    .OUT1(_047_)
  );
  INVR01 _093_ (
    .IN1(in0[8]),
    .OUT1(_048_)
  );
  INVR01 _094_ (
    .IN1(in0[9]),
    .OUT1(_049_)
  );
  INVR01 _095_ (
    .IN1(in0[10]),
    .OUT1(_050_)
  );
  INVR01 _096_ (
    .IN1(in0[11]),
    .OUT1(_051_)
  );
  INVR01 _097_ (
    .IN1(in0[12]),
    .OUT1(_052_)
  );
  INVR01 _098_ (
    .IN1(in0[13]),
    .OUT1(_053_)
  );
  INVR01 _099_ (
    .IN1(in0[14]),
    .OUT1(_054_)
  );
  NOR200 _100_ (
    .IN1(_040_),
    .IN2(in0[0]),
    .OUT1(_055_)
  );
  XNR201 _101_ (
    .IN1(_040_),
    .IN2(in0[0]),
    .OUT1(out[0])
  );
  NND201 _102_ (
    .IN1(_041_),
    .IN2(in0[1]),
    .OUT1(_056_)
  );
  XNR201 _103_ (
    .IN1(in1[1]),
    .IN2(in0[1]),
    .OUT1(_057_)
  );
  ORND01 _104_ (
    .A(_040_),
    .B(in0[0]),
    .C(_057_),
    .OUT1(_058_)
  );
  XNR201 _105_ (
    .IN1(_055_),
    .IN2(_057_),
    .OUT1(out[1])
  );
  NND201 _106_ (
    .IN1(_056_),
    .IN2(_058_),
    .OUT1(_059_)
  );
  NOR200 _107_ (
    .IN1(in1[2]),
    .IN2(_044_),
    .OUT1(_060_)
  );
  XNR201 _108_ (
    .IN1(in1[2]),
    .IN2(in0[2]),
    .OUT1(_061_)
  );
  INVR01 _109_ (
    .IN1(_061_),
    .OUT1(_062_)
  );
  ADNR01 _110_ (
    .A(_056_),
    .B(_058_),
    .C(_062_),
    .OUT1(_063_)
  );
  NOR200 _111_ (
    .IN1(_059_),
    .IN2(_061_),
    .OUT1(_064_)
  );
  NOR200 _112_ (
    .IN1(_063_),
    .IN2(_064_),
    .OUT1(out[2])
  );
  NOR200 _113_ (
    .IN1(_060_),
    .IN2(_063_),
    .OUT1(_065_)
  );
  NND201 _114_ (
    .IN1(_042_),
    .IN2(in0[3]),
    .OUT1(_066_)
  );
  XNR201 _115_ (
    .IN1(in1[3]),
    .IN2(in0[3]),
    .OUT1(_067_)
  );
  ORND01 _116_ (
    .A(_060_),
    .B(_063_),
    .C(_067_),
    .OUT1(_068_)
  );
  XNR201 _117_ (
    .IN1(_065_),
    .IN2(_067_),
    .OUT1(out[3])
  );
  NND201 _118_ (
    .IN1(_066_),
    .IN2(_068_),
    .OUT1(_069_)
  );
  NOR200 _119_ (
    .IN1(in1[4]),
    .IN2(_045_),
    .OUT1(_070_)
  );
  XNR201 _120_ (
    .IN1(in1[4]),
    .IN2(in0[4]),
    .OUT1(_071_)
  );
  INVR01 _121_ (
    .IN1(_071_),
    .OUT1(_072_)
  );
  ADNR01 _122_ (
    .A(_066_),
    .B(_068_),
    .C(_072_),
    .OUT1(_073_)
  );
  NOR200 _123_ (
    .IN1(_069_),
    .IN2(_071_),
    .OUT1(_074_)
  );
  NOR200 _124_ (
    .IN1(_073_),
    .IN2(_074_),
    .OUT1(out[4])
  );
  NOR200 _125_ (
    .IN1(_070_),
    .IN2(_073_),
    .OUT1(_075_)
  );
  NND201 _126_ (
    .IN1(_043_),
    .IN2(in0[5]),
    .OUT1(_076_)
  );
  XNR201 _127_ (
    .IN1(in1[5]),
    .IN2(in0[5]),
    .OUT1(_077_)
  );
  ORND01 _128_ (
    .A(_070_),
    .B(_073_),
    .C(_077_),
    .OUT1(_078_)
  );
  XNR201 _129_ (
    .IN1(_075_),
    .IN2(_077_),
    .OUT1(out[5])
  );
  NND201 _130_ (
    .IN1(_076_),
    .IN2(_078_),
    .OUT1(_079_)
  );
  NOR200 _131_ (
    .IN1(in1[6]),
    .IN2(_046_),
    .OUT1(_080_)
  );
  XNR201 _132_ (
    .IN1(in1[6]),
    .IN2(in0[6]),
    .OUT1(_081_)
  );
  INVR01 _133_ (
    .IN1(_081_),
    .OUT1(_082_)
  );
  ADNR01 _134_ (
    .A(_076_),
    .B(_078_),
    .C(_082_),
    .OUT1(_083_)
  );
  NOR200 _135_ (
    .IN1(_079_),
    .IN2(_081_),
    .OUT1(_084_)
  );
  NOR200 _136_ (
    .IN1(_083_),
    .IN2(_084_),
    .OUT1(out[6])
  );
  NOR200 _137_ (
    .IN1(_080_),
    .IN2(_083_),
    .OUT1(_000_)
  );
  NOR200 _138_ (
    .IN1(in1[7]),
    .IN2(_047_),
    .OUT1(_001_)
  );
  AND201 _139_ (
    .IN1(in1[7]),
    .IN2(_047_),
    .OUT1(_002_)
  );
  NOR200 _140_ (
    .IN1(_001_),
    .IN2(_002_),
    .OUT1(_003_)
  );
  XNR201 _141_ (
    .IN1(_000_),
    .IN2(_003_),
    .OUT1(out[7])
  );
  NOR200 _142_ (
    .IN1(in1[8]),
    .IN2(_048_),
    .OUT1(_004_)
  );
  XNR201 _143_ (
    .IN1(in1[8]),
    .IN2(in0[8]),
    .OUT1(_005_)
  );
  INVR01 _144_ (
    .IN1(_005_),
    .OUT1(_006_)
  );
  NOR200 _145_ (
    .IN1(_000_),
    .IN2(_002_),
    .OUT1(_007_)
  );
  NOR300 _146_ (
    .IN1(_080_),
    .IN2(_083_),
    .IN3(_001_),
    .OUT1(_008_)
  );
  NOR300 _147_ (
    .IN1(_002_),
    .IN2(_006_),
    .IN3(_008_),
    .OUT1(_009_)
  );
  NOR300 _148_ (
    .IN1(_001_),
    .IN2(_005_),
    .IN3(_007_),
    .OUT1(_010_)
  );
  NOR200 _149_ (
    .IN1(_009_),
    .IN2(_010_),
    .OUT1(out[8])
  );
  NOR200 _150_ (
    .IN1(_004_),
    .IN2(_009_),
    .OUT1(_011_)
  );
  NOR200 _151_ (
    .IN1(in1[9]),
    .IN2(_049_),
    .OUT1(_012_)
  );
  AND201 _152_ (
    .IN1(in1[9]),
    .IN2(_049_),
    .OUT1(_013_)
  );
  NOR200 _153_ (
    .IN1(_012_),
    .IN2(_013_),
    .OUT1(_014_)
  );
  XNR201 _154_ (
    .IN1(_011_),
    .IN2(_014_),
    .OUT1(out[9])
  );
  NOR200 _155_ (
    .IN1(in1[10]),
    .IN2(_050_),
    .OUT1(_015_)
  );
  XNR201 _156_ (
    .IN1(in1[10]),
    .IN2(in0[10]),
    .OUT1(_016_)
  );
  INVR01 _157_ (
    .IN1(_016_),
    .OUT1(_017_)
  );
  NOR300 _158_ (
    .IN1(_004_),
    .IN2(_009_),
    .IN3(_012_),
    .OUT1(_018_)
  );
  OR2101 _159_ (
    .IN1(_013_),
    .IN2(_018_),
    .OUT1(_019_)
  );
  NOR300 _160_ (
    .IN1(_013_),
    .IN2(_017_),
    .IN3(_018_),
    .OUT1(_020_)
  );
  XNR201 _161_ (
    .IN1(_016_),
    .IN2(_019_),
    .OUT1(out[10])
  );
  NOR200 _162_ (
    .IN1(_015_),
    .IN2(_020_),
    .OUT1(_021_)
  );
  NOR200 _163_ (
    .IN1(in1[11]),
    .IN2(_051_),
    .OUT1(_022_)
  );
  AND201 _164_ (
    .IN1(in1[11]),
    .IN2(_051_),
    .OUT1(_023_)
  );
  NOR200 _165_ (
    .IN1(_022_),
    .IN2(_023_),
    .OUT1(_024_)
  );
  XNR201 _166_ (
    .IN1(_021_),
    .IN2(_024_),
    .OUT1(out[11])
  );
  NOR200 _167_ (
    .IN1(in1[12]),
    .IN2(_052_),
    .OUT1(_025_)
  );
  XNR201 _168_ (
    .IN1(in1[12]),
    .IN2(in0[12]),
    .OUT1(_026_)
  );
  INVR01 _169_ (
    .IN1(_026_),
    .OUT1(_027_)
  );
  NOR300 _170_ (
    .IN1(_015_),
    .IN2(_020_),
    .IN3(_022_),
    .OUT1(_028_)
  );
  OR2101 _171_ (
    .IN1(_023_),
    .IN2(_028_),
    .OUT1(_029_)
  );
  NOR300 _172_ (
    .IN1(_023_),
    .IN2(_027_),
    .IN3(_028_),
    .OUT1(_030_)
  );
  XNR201 _173_ (
    .IN1(_026_),
    .IN2(_029_),
    .OUT1(out[12])
  );
  NOR200 _174_ (
    .IN1(_025_),
    .IN2(_030_),
    .OUT1(_031_)
  );
  XNR201 _175_ (
    .IN1(in1[13]),
    .IN2(in0[13]),
    .OUT1(_032_)
  );
  ORND01 _176_ (
    .A(_025_),
    .B(_030_),
    .C(_032_),
    .OUT1(_033_)
  );
  XNR201 _177_ (
    .IN1(_031_),
    .IN2(_032_),
    .OUT1(out[13])
  );
  ORND01 _178_ (
    .A(in1[13]),
    .B(_053_),
    .C(_033_),
    .OUT1(_034_)
  );
  NOR200 _179_ (
    .IN1(in1[14]),
    .IN2(_054_),
    .OUT1(_035_)
  );
  NND201 _180_ (
    .IN1(in1[14]),
    .IN2(_054_),
    .OUT1(_036_)
  );
  XNR201 _181_ (
    .IN1(in1[14]),
    .IN2(_054_),
    .OUT1(_037_)
  );
  XNR201 _182_ (
    .IN1(_034_),
    .IN2(_037_),
    .OUT1(out[14])
  );
  ADNR01 _183_ (
    .A(_034_),
    .B(_036_),
    .C(_035_),
    .OUT1(_038_)
  );
  XNR201 _184_ (
    .IN1(in1[15]),
    .IN2(in0[15]),
    .OUT1(_039_)
  );
  XNR201 _185_ (
    .IN1(_038_),
    .IN2(_039_),
    .OUT1(out[15])
  );
endmodule

(* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:619" *)
module ZeroComparator_0x422b1f52edd46a85(clk, in_, out, reset);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:621" *)
  input clk;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:622" *)
  input [15:0] in_;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:623" *)
  output out;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:624" *)
  input reset;
  OR4101 _05_ (
    .IN1(in_[0]),
    .IN2(in_[3]),
    .IN3(in_[5]),
    .IN4(in_[6]),
    .OUT1(_00_)
  );
  OR4101 _06_ (
    .IN1(in_[9]),
    .IN2(in_[10]),
    .IN3(in_[12]),
    .IN4(in_[15]),
    .OUT1(_01_)
  );
  OR2101 _07_ (
    .IN1(_00_),
    .IN2(_01_),
    .OUT1(_02_)
  );
  OR4101 _08_ (
    .IN1(in_[1]),
    .IN2(in_[2]),
    .IN3(in_[4]),
    .IN4(in_[7]),
    .OUT1(_03_)
  );
  OR4101 _09_ (
    .IN1(in_[8]),
    .IN2(in_[11]),
    .IN3(in_[13]),
    .IN4(in_[14]),
    .OUT1(_04_)
  );
  NOR300 _10_ (
    .IN1(_02_),
    .IN2(_03_),
    .IN3(_04_),
    .OUT1(out)
  );
endmodule

(* top =  1  *)
(* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:11" *)
module gcd(clk, req_msg, req_rdy, req_val, reset, resp_msg, resp_rdy, resp_val);
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:13" *)
  input clk;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:30" *)
  wire [1:0] \ctrl$a_mux_sel ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:34" *)
  wire \ctrl$a_reg_en ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:32" *)
  wire \ctrl$b_mux_sel ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:33" *)
  wire \ctrl$b_reg_en ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:26" *)
  wire \ctrl$clk ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:27" *)
  wire \ctrl$is_a_lt_b ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:24" *)
  wire \ctrl$is_b_zero ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:35" *)
  wire \ctrl$req_rdy ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:28" *)
  wire \ctrl$req_val ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:29" *)
  wire \ctrl$reset ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:25" *)
  wire \ctrl$resp_rdy ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:31" *)
  wire \ctrl$resp_val ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:54" *)
  wire [1:0] \dpath$a_mux_sel ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:61" *)
  wire \dpath$a_reg_en ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:58" *)
  wire \dpath$b_mux_sel ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:60" *)
  wire \dpath$b_reg_en ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:55" *)
  wire \dpath$clk ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:64" *)
  wire \dpath$is_a_lt_b ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:62" *)
  wire \dpath$is_b_zero ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:57" *)
  wire [15:0] \dpath$req_msg_a ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:56" *)
  wire [15:0] \dpath$req_msg_b ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:59" *)
  wire \dpath$reset ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:63" *)
  wire [15:0] \dpath$resp_msg ;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:14" *)
  input [31:0] req_msg;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:15" *)
  output req_rdy;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:16" *)
  input req_val;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:17" *)
  input reset;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:18" *)
  output [15:0] resp_msg;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:19" *)
  input resp_rdy;
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:20" *)
  output resp_val;
  (* module_not_derived = 32'd1 *)
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:37" *)
  GcdUnitCtrlRTL_0x4d0fc71ead8d3d9e ctrl (
    .a_mux_sel(\ctrl$a_mux_sel ),
    .a_reg_en(\ctrl$a_reg_en ),
    .b_mux_sel(\ctrl$b_mux_sel ),
    .b_reg_en(\ctrl$b_reg_en ),
    .clk(clk),
    .is_a_lt_b(\ctrl$is_a_lt_b ),
    .is_b_zero(\ctrl$is_b_zero ),
    .req_rdy(\ctrl$req_rdy ),
    .req_val(req_val),
    .reset(reset),
    .resp_rdy(resp_rdy),
    .resp_val(\ctrl$resp_val )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/workspaces/OpenLane-scl-ref/designs/gcd_scl_ref/src/gcd.v:66" *)
  GcdUnitDpathRTL_0x4d0fc71ead8d3d9e dpath (
    .a_mux_sel(\ctrl$a_mux_sel ),
    .a_reg_en(\ctrl$a_reg_en ),
    .b_mux_sel(\ctrl$b_mux_sel ),
    .b_reg_en(\ctrl$b_reg_en ),
    .clk(clk),
    .is_a_lt_b(\ctrl$is_a_lt_b ),
    .is_b_zero(\ctrl$is_b_zero ),
    .req_msg_a(req_msg[31:16]),
    .req_msg_b(req_msg[15:0]),
    .reset(reset),
    .resp_msg(\dpath$resp_msg )
  );
  assign \ctrl$clk  = clk;
  assign \ctrl$req_val  = req_val;
  assign \ctrl$reset  = reset;
  assign \ctrl$resp_rdy  = resp_rdy;
  assign \dpath$a_mux_sel  = \ctrl$a_mux_sel ;
  assign \dpath$a_reg_en  = \ctrl$a_reg_en ;
  assign \dpath$b_mux_sel  = \ctrl$b_mux_sel ;
  assign \dpath$b_reg_en  = \ctrl$b_reg_en ;
  assign \dpath$clk  = clk;
  assign \dpath$is_a_lt_b  = \ctrl$is_a_lt_b ;
  assign \dpath$is_b_zero  = \ctrl$is_b_zero ;
  assign \dpath$req_msg_a  = req_msg[31:16];
  assign \dpath$req_msg_b  = req_msg[15:0];
  assign \dpath$reset  = reset;
  assign req_rdy = \ctrl$req_rdy ;
  assign resp_msg = \dpath$resp_msg ;
  assign resp_val = \ctrl$resp_val ;
endmodule
